include: package:very_good_analysis/analysis_options.3.0.1.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore